stages: [test, deploy]
test:
  stage: test
  image: node:24
  before_script:
    - cd api
    - npm install
  script:
    - npm test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy_staging:
  stage: deploy
  needs:
    - test
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
  script:
    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no "$STAGING_USER@$STAGING_HOST" "cd /opt/devops-notes && git pull && docker-compose up -d --build"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
